# zizmor configuration
# https://docs.zizmor.sh/configuration/

rules:
  unpinned-uses:
    ignore:
      - action.yaml
      - devenv/action.yaml
      - .github/actions/devenv/action.yaml
      - changeset-policy.yml
      - ci.yml
      - docs.yml
      - publish.yml
      - release.yml

  github-env:
    ignore:
      - action.yaml
      - devenv/action.yaml
      - .github/actions/devenv/action.yaml

  template-injection:
    ignore:
      - publish.yml
      - release.yml
      - release-pr.yml
      - changeset-policy.yml

  artipacked:
    ignore:
      - publish.yml
      - release.yml

  cache-poisoning:
    ignore:
      - devenv/action.yaml
