name: monosecret
description: Dart SDK for invoking Monosecret and loading secrets into Dart applications.
version: 0.1.0
repository: https://github.com/ifiokjr/monosecret
resolution: workspace

environment:
  sdk: ^3.5.0

dev_dependencies:
  coverage: ^1.9.0
  test: ^1.25.0
