[package]
name = "monosecret_derive-example"
version = "0.0.0"
edition = "2021"
publish = false

[lints]
workspace = true

[[bin]]
name = "derive"
path = "derive.rs"

[dependencies]
monosecret = { workspace = true }
monosecret_derive = { workspace = true }
secrecy = { workspace = true, default-features = true }
serde = { workspace = true, default-features = true }
